//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public Achievement()
        {
            this.UserAchievements = new HashSet<UserAchievement>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Points { get; set; }
    
        public virtual ICollection<UserAchievement> UserAchievements { get; set; }
    }
}
