//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.MotherCoupons = new HashSet<MotherCoupon>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Discount { get; set; }
        public int CouponType { get; set; }
        public int MinOrderValue { get; set; }
        public bool IsAvailableForAll { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime Enddate { get; set; }
        public int AvailType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotherCoupon> MotherCoupons { get; set; }
    }
}
