//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBankDetail
    {
        public int Id { get; set; }
        public int MotherId { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public string AccountHolderName { get; set; }
        public string IFSC_Code { get; set; }
    
        public virtual MotherTbl MotherTbl { get; set; }
    }
}
