//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherStatement
    {
        public int Id { get; set; }
        public int MotherId { get; set; }
        public System.DateTime Date { get; set; }
        public string TransactionNo { get; set; }
        public decimal AmountReceived { get; set; }
        public string Remarks { get; set; }
    
        public virtual MotherTbl MotherTbl { get; set; }
    }
}
