//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherTbl
    {
        public MotherTbl()
        {
            this.MortherOrders = new HashSet<MortherOrder>();
            this.MotherAnswers = new HashSet<MotherAnswer>();
            this.MotherBankDetails = new HashSet<MotherBankDetail>();
            this.MotherCarts = new HashSet<MotherCart>();
            this.MotherCoupons = new HashSet<MotherCoupon>();
            this.MotherDailySchedules = new HashSet<MotherDailySchedule>();
            this.MotherDishes = new HashSet<MotherDish>();
            this.MotherGalleries = new HashSet<MotherGallery>();
            this.MotherStatements = new HashSet<MotherStatement>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ApplicationNo { get; set; }
        public int Ratings { get; set; }
        public string Description { get; set; }
        public string LOfflineTime { get; set; }
        public string DOfflineTime { get; set; }
        public string LDeliveryTime { get; set; }
        public string DDeliveryTime { get; set; }
        public string ProfilePhoto { get; set; }
        public string CoverPhoto { get; set; }
        public decimal Commision { get; set; }
        public decimal WalletAmount { get; set; }
    
        public virtual ICollection<MortherOrder> MortherOrders { get; set; }
        public virtual ICollection<MotherAnswer> MotherAnswers { get; set; }
        public virtual ICollection<MotherBankDetail> MotherBankDetails { get; set; }
        public virtual ICollection<MotherCart> MotherCarts { get; set; }
        public virtual ICollection<MotherCoupon> MotherCoupons { get; set; }
        public virtual ICollection<MotherDailySchedule> MotherDailySchedules { get; set; }
        public virtual ICollection<MotherDish> MotherDishes { get; set; }
        public virtual ICollection<MotherGallery> MotherGalleries { get; set; }
        public virtual ICollection<MotherStatement> MotherStatements { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
