//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherDish
    {
        public MotherDish()
        {
            this.MotherCartDetails = new HashSet<MotherCartDetail>();
            this.MotherDishDailySchedules = new HashSet<MotherDishDailySchedule>();
            this.MotherDishReviews = new HashSet<MotherDishReview>();
            this.MotherOrderDetails = new HashSet<MotherOrderDetail>();
        }
    
        public int Id { get; set; }
        public int MotherId { get; set; }
        public int DishId { get; set; }
        public int Limit { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsMainDish { get; set; }
        public bool IsSignatureDish { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual ICollection<MotherCartDetail> MotherCartDetails { get; set; }
        public virtual ICollection<MotherDishDailySchedule> MotherDishDailySchedules { get; set; }
        public virtual MotherTbl MotherTbl { get; set; }
        public virtual ICollection<MotherDishReview> MotherDishReviews { get; set; }
        public virtual ICollection<MotherOrderDetail> MotherOrderDetails { get; set; }
    }
}
