//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.MortherOrders = new HashSet<MortherOrder>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Tax { get; set; }
        public decimal Packing { get; set; }
        public decimal Delivery { get; set; }
        public decimal Total { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<int> CouponId { get; set; }
        public decimal DiscountAmount { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual ICollection<MortherOrder> MortherOrders { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
