//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int TransactionId { get; set; }
        public int Mode { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceLink { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
