//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotificationsMessageLog
    {
        public int PushNotificationsMessageLogsId { get; set; }
        public string DeviceToken { get; set; }
        public int DeviceType { get; set; }
        public string DeviceID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateProcessed { get; set; }
        public Nullable<int> FKReceiverUserId { get; set; }
        public Nullable<int> FKQueuedPushNotificationsId { get; set; }
        public string ErrorMessage { get; set; }
        public string JsonData { get; set; }
    }
}
