//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueuedPushNotification
    {
        public int QueuedPushNotificationsId { get; set; }
        public int NotificationType { get; set; }
        public string Message { get; set; }
        public int Badge { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string JsonData { get; set; }
        public Nullable<int> FKSenderUserId { get; set; }
        public int FKReceiverUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
