//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginSession
    {
        public System.Guid UserLoginSessionID { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoggedInTime { get; set; }
        public Nullable<System.DateTime> LoggedOutTime { get; set; }
        public bool SessionExpired { get; set; }
        public Nullable<System.DateTime> LastActivityTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UniqueDeviceId { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public string TokenVOIP { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
    }
}
