//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApniMaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressTbl
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int City { get; set; }
        public int Province { get; set; }
        public string Address { get; set; }
        public string Longitute { get; set; }
        public string Latitute { get; set; }
        public Nullable<int> NickName { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
    }
}
